name: Test Workflow
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Java
        run: |
          echo ${{ vars.BUILD_VARIABLES}} > tmp.pkvars.hcl
          ls -al
