name: Packer Workflow
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SECRET: ${{ secrets.SECRET }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          packer_version: 1.10.1
      - name: Making the JSON file
        run: echo "${{ secrets.MY_JSON_SECRET }}" > csye6225.json && mv csye6225.json packer/csye6225.json
      - name: LIsitng the files
        run: ls -al
      - name: Build with Packer
        run: cd packer && packer init .
      - name: Validate with Packer
        run: cd packer && ls -al 
