name: Packer Workflow
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SECRET: ${{ secrets.SECRET }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          packer_version: 1.10.1
      - name: Revealing secrets
        run: echo $SECRET
      - name: Build with Packer
        run: cd packer && packer init .
      - name: Validate with Packer
        run: cd packer && packer validate .
