name: Packer Workflow
on:
  pull_request:
    types:
      - closed
    branches:
      - main
    
jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
          cache: maven
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.2
      - name: Build with Maven
        run: mvn --batch-mode package      
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          packer_version: 1.10.1
      - name: Making the JSON file
        uses: jsdaniell/create-json@v1.2.3
        with:
          name: "csye6225.json"
          json: ${{ secrets.PACKER_GCP}}
      - name: LIsitng the files
        run: sudo mv csye6225.json packer/csye6225.json
      - name: Build with Packer
        run: cd packer && packer init .
      - name: Validate with Packer
        run: cd packer && packer build .
