name: Update Workflow
on: 
    workflow_run:
        workflows: ["Packer Workflow"]
        types:
            - completed
        branches:
            - main
jobs:
    update:
        runs-on: ubuntu-latest
        steps:
            - name: Print a message
              run: echo "The completed workflow has finished!"
