name: Update Workflow
on:
    pull_request:
        branches:
            - main
jobs:
    update-template:
        runs-on: ubuntu-latest
        steps:
            - id: 'auth'
              uses: 'google-github-actions/auth@v2'
              with:
                credentials_json: '${{ secrets.GCP_SA_KEY }}'
                create_credentials_file: true
                
            - name: 'Set up Cloud SDK'
              uses: 'google-github-actions/setup-gcloud@v2'
              with:
                version: '>= 363.0.0'
                project_id: '${{ vars.GCP_PROJECT_ID }}'
            - name: 'Use gcloud CLI'
              run: |
                gcloud auth activate-service-account --key-file=${{ steps.auth.outputs.credentials_file_path }}
                gcloud projects list
                gcloud compute instance-templates create csye6225-vm-template \
                  --machine-type e2-medium \
                  --boot-disk-size 40 \
                  --boot-disk-type pd-balanced \
                  --image projects/csye6225dev-415015/global/images/csye-centos-stream-8 \
                  --network csye6225-vpc \
                  --subnet webapp \
                  --tags=webapp-firewall \
                  --metadata=db_password=DB_PASSWORD,db_username=DB_USERNAME,db_name=DB_NAME,db_host=DB_HOST,db_port=5432,project_id=PROJECT_ID,topic_id=TOPIC_ID \
                  --service-account=loggingserviceaccount@csye-6225-414418.iam.gserviceaccount.com \
                  --scopes=https://www.googleapis.com/auth/cloud-platform \
                  --boot-disk-kms-key projects/csye-6225-414418/locations/us-east1/keyRings/my-key-ring-zmtYx/cryptoKeys/vm-crypto-key-zmtYx